uint64 timestamp	# time since system start (microseconds)
uint32 device_id	# Sensor ID that must be unique for each baro sensor and must not change

float32 windspeed		# Wind speed(m/sec)
float32 wind_direction		# Wind direction (deg)

float32 accuracy_windspeed		# Wind speed accuracy (m/sec)
float32 accuracy_direction		# Wind direction accuracy (deg)

float32 pressure	# static pressure measurement in millibar

float32 temperature	# static temperature measurement in deg C
